import {useEffect,useState} from 'react';
type Citation={source_id:string;start:number;end:number;quote:string};
type Finding={id:string;title:string;severity:string;description:string;impact:string;recommendation:string;citations:Citation[]};
type Report={title:string;passed:boolean;boundary:string;base_version:string;sha256:string;scope:{summary:string;files:string[];focus:string[]};audit:{summary:string;coverage:{path:string;summary:string;citations:Citation[]}[];findings:Finding[];limitations:string[]}|null;response:{summary:string;responses:{finding_id:string;position:string;reason:string;suggestion:string;citations:Citation[]}[]}|null;verdict:{summary:string;decisions:{finding_id:string;decision:string;reason:string;citations:Citation[]}[];limitations:string[]}|null;open_findings:Finding[];sources:Record<string,{text:string;sha256:string}>;analysis_error:string|null;validation:{errors:string[]}};
function Citations({items,report}:{items:Citation[];report:Report}){return <>{items.map((c,i)=><details key={i}><summary>代码依据 · {c.source_id.replace(/^file:/,'')} · 第 {c.start}–{c.end} 行</summary><blockquote>{c.quote}</blockquote><pre>{report.sources[c.source_id]?.text.split('\n').slice(Math.max(0,c.start-1),c.end).map((line,k)=>`${c.start+k}: ${line}`).join('\n')||'引用来源缺失，请查看报告错误'}</pre></details>)}</>;}
export function CodeReviewReport({runId,status,revision,onFix,activeVersion,disabled}:{runId:string;status:string;revision:number;onFix:()=>void;activeVersion:string|null;disabled:boolean}){
  const [report,setReport]=useState<Report|null>(null),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();setError('');fetch('/api/runs/'+runId+'/report',{signal:c.signal}).then(async r=>{if(r.status===404)return null;if(!r.ok)throw Error('审查报告读取失败，请重试');return r.json();}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[runId,revision]);
  return <div className="task-report document-report"><section className="report-intro"><div className="eyebrow">CODE REVIEW</div><h3>独立代码审查</h3><p>{report?.boundary||'确认版本与文件范围后，主程检查代码，程序逐项回应，主程复核结论。'}</p>{error&&<p className="run-error" role="alert">{error}</p>}
    {!report&&<p>{status==='waiting_confirmation'?'等待你确认审查范围。':['failed','cancelled'].includes(status)?'本轮未形成最终报告，请查看阶段日志。':'审查进行中，团队页可查看角色交接。'}</p>}
    {report&&<><p className={report.passed?'check-pass':'check-fail'}>{report.passed?'审查报告完成':'报告未通过门禁 · 草稿不可作为修复依据'}</p><p>审查版本 {report.base_version.slice(0,8)} · 待处理 {report.open_findings.length} 项{report.passed&&report.open_findings.length===0?'（仅限本次静态审查范围）':''}</p>
      <a className="subtle report-download" href={'/api/runs/'+runId+'/report/export'}>下载代码审查 ZIP</a>{report.passed&&!!report.open_findings.length&&<button className="subtle" disabled={disabled||report.base_version!==activeVersion} onClick={onFix}>填写修复需求</button>}</>}
  </section>
  {report&&<><section className="report-analysis"><h3>逐文件覆盖</h3><p>{report.audit?.summary||'尚无有效审查交付。'}</p>{report.audit?.coverage.map((c,i)=><div className="document-section" key={i}><strong>{c.path}</strong><p>{c.summary}</p><Citations items={c.citations} report={report}/></div>)}</section>
    <section className="report-analysis"><h3>问题与回应</h3>{report.audit?.findings.length===0&&<p>本次未提出问题；这不证明代码没有缺陷，运行表现需独立测试与试玩。</p>}
    {report.audit?.findings.map(f=>{const response=report.response?.responses.find(r=>r.finding_id===f.id),decision=report.verdict?.decisions.find(d=>d.finding_id===f.id);return <article className="document-section" key={f.id}><div className="card-label"><b>{f.title}</b><span>{f.severity==='blocking'?'阻断':'建议'}</span></div><p>{f.description}</p><p>影响：{f.impact}</p><p>建议：{f.recommendation}</p><Citations items={f.citations} report={report}/><h4>程序回应 · {response?.position==='agree'?'同意':response?'有异议':'未完成'}</h4><p>{response?.reason}</p><p>{response?.suggestion}</p>{response&&<Citations items={response.citations} report={report}/>}<h4>主程复核 · {decision?({confirmed:'问题成立',dismissed:'已排除',unresolved:'待人工确认'}[decision.decision]||decision.decision):'未完成'}</h4><p>{decision?.reason}</p>{decision&&<Citations items={decision.citations} report={report}/>}</article>;})}
    </section><section className="report-analysis"><h3>复核与限制</h3><p>{report.verdict?.summary||'未形成有效复核。'}</p>{report.analysis_error&&<p className="run-error">{report.analysis_error}</p>}{report.validation.errors.map((v,i)=><p className="run-error" key={i}>{v}</p>)}{[...(report.audit?.limitations||[]),...(report.verdict?.limitations||[])].map((v,i)=><p className="inline-note" key={i}>{v}</p>)}<details><summary>审查来源摘要</summary><pre>{JSON.stringify({report_sha256:report.sha256,sources:Object.fromEntries(Object.entries(report.sources).map(([k,v])=>[k,v.sha256]))},null,2)}</pre></details></section></>}
  </div>;
}
