import {useEffect,useState} from 'react';
type Citation={source_id:string;start:number;end:number;quote:string};
type Statement={kind:'fact'|'inference'|'hypothesis';text:string;citations:Citation[]};
type Direction={id:string;title:string;summary:string;assessments:{criterion:string;statement:Statement}[];next_steps:string[]};
type Report={title:string;base_version:string|null;passed:boolean;boundary:string;evidence_scope:string;sources:Record<string,{label:string;text:string;url?:string;final_url?:string;fetched_at?:string;truncated?:boolean;sha256:string}>;source_fetches:{url:string;status:string;error?:string}[];scope:{questions:{id:string;text:string}[];criteria:string[]};result:{summary:string;answers:{question_id:string;statement:Statement}[];directions:Direction[];recommendation:string;rationale:Statement;backlog:{title:string;priority:string;rationale:string;validation:string}[];unknowns:string[]}|null;review:{summary:string;limitations:string[]}|null;analysis_error:string|null;validation:{errors:string[]}};
function Evidence({statement,report}:{statement:Statement;report:Report}){return <div className="research-statement"><small>{({fact:'来源事实',inference:'依据推断',hypothesis:'待验证假设'})[statement.kind]}</small><p>{statement.text}</p>{statement.citations.map((c,i)=><details key={i}><summary>依据 · {report.sources[c.source_id]?.label||c.source_id} · {c.start}–{c.end} 行</summary><blockquote>{c.quote}</blockquote></details>)}</div>;}
export function ResearchReport({runId,status,revision,activeVersion,disabled,onChoose}:{runId:string;status:string;revision:number;activeVersion:string|null;disabled:boolean;onChoose:(direction:Direction)=>void}){
  const [report,setReport]=useState<Report|null>(null),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();setError('');fetch('/api/runs/'+runId+'/report',{signal:c.signal}).then(async r=>{if(r.status===404)return null;if(!r.ok)throw Error('调研报告读取失败，请重试');return r.json();}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[runId,revision]);
  return <div className="task-report document-report"><section className="report-intro"><div className="eyebrow">DIRECTION RESEARCH</div><h3>{report?.title||'先找到值得做的方向'}</h3><p>{report?.boundary||'确认问题、比较方向和来源后，策划形成分析与建议，制作人复核。'}</p>{error&&<p className="run-error">{error}</p>}{!report&&<p>{status==='waiting_confirmation'?'等待确认调研范围。':['failed','cancelled'].includes(status)?'本轮没有形成最终报告。':'正在读取来源或分析方向，可查看阶段日志。'}</p>}{report&&<><p className={report.passed?'check-pass':'check-fail'}>{report.passed?'调研报告完成':'调研未通过门禁 · 请查看来源与错误'}</p><p>{report.evidence_scope}</p><a className="subtle report-download" href={'/api/runs/'+runId+'/report/export'}>下载调研报告 ZIP</a></>}</section>
    {report?.result&&<><section className="report-analysis"><h3>问题与结论</h3><p>{report.result.summary}</p>{report.result.answers.map((a,i)=><article className="document-section" key={i}><h4>{report.scope.questions.find(q=>q.id===a.question_id)?.text||a.question_id}</h4><Evidence statement={a.statement} report={report}/></article>)}</section>
      <section className="report-analysis"><h3>方向比较</h3><div className="research-matrix"><table><thead><tr><th>比较维度</th>{report.result.directions.map((d,i)=><th key={i}>{d.title}</th>)}</tr></thead><tbody>{report.scope.criteria.map((criterion,i)=><tr key={i}><th>{criterion}</th>{report.result!.directions.map((d,j)=><td key={j}>{d.assessments.find(a=>a.criterion===criterion)?<Evidence statement={d.assessments.find(a=>a.criterion===criterion)!.statement} report={report}/>:<span>缺少对应比较</span>}</td>)}</tr>)}</tbody></table></div>
      {report.result.directions.map((d,i)=><article className="document-section" key={i}><div className="card-label"><b>{d.title}</b>{d.id===report.result!.recommendation&&<span>策划建议</span>}</div><p>{d.summary}</p><ul>{d.next_steps.map((v,j)=><li key={j}>{v}</li>)}</ul>{report.passed&&<button className="subtle" disabled={disabled||report.base_version!==activeVersion} onClick={()=>onChoose(d)}>采用「{d.title}」填写需求</button>}</article>)}<h3>推荐依据</h3><Evidence statement={report.result.rationale} report={report}/></section>
      <section className="report-analysis"><h3>建议待做清单</h3>{report.result.backlog.map((item,i)=><article className="document-section" key={i}><strong>{({must:'优先',should:'随后',could:'可选'} as Record<string,string>)[item.priority]} · {item.title}</strong><p>{item.rationale}</p><p>验证方式：{item.validation}</p></article>)}<h3>尚待核实</h3><ul>{report.result.unknowns.map((v,i)=><li key={i}>{v}</li>)}</ul></section></>}
    {report&&<section className="report-analysis"><h3>制作人复核</h3><p>{report.review?.summary||'没有有效复核。'}</p>{report.analysis_error&&<p className="run-error">{report.analysis_error}</p>}{report.validation.errors.map((v,i)=><p className="run-error" key={i}>{v}</p>)}{report.review?.limitations.map((v,i)=><p className="inline-note" key={i}>{v}</p>)}<h3>来源记录</h3>{report.source_fetches.map((f,i)=><p className={f.status==='ready'?'inline-note':'run-error'} key={i}>{f.url} · {f.status==='ready'?'已读取':f.error}</p>)}{Object.entries(report.sources).map(([id,s])=><details className="document-section" key={id}><summary>{s.label}</summary>{s.final_url&&<p>网页：{s.final_url}<br/>读取：{s.fetched_at}{s.truncated?' · 正文已截断':''}</p>}<pre>{s.text}</pre><p className="inline-note">来源编号 {id} · SHA-256 {s.sha256}</p></details>)}</section>}
  </div>;
}
